### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by f73chen** [oicr-gsi/callability#2]
Fix: change these two lines in python section to:
total_count = int(float("${TOTAL}"))
pass_count = int(float("${PASS}"))

Reason:
https://stackoverflow.com/questions/1841565/valueerror-invalid-literal-for-int-with-base-10

**Comment by mlaszloffy** [comment]
Thanks Grace for the report, this fix has been added to the linked PR.
